name: CustomCSWeapon
main: com.ericlam.mc.csweapon.CustomCSWeapon
version: ${project.version}
api-version: "1.18"
author: Hydranapse_
depend: [WeaponMechanics, DragoniteMC-Core]
commands:
  csw-reload:
    description: reload command
  csw-scope:
    description: left click scope or sneak scope
