molotov-duration: 20
molotov:
  - Molotov
scope-skin: #[material]:[damage]
  AWM: IRON_NUGGET
  M14: IRON_NUGGET
  M24: IRON_NUGGET
  SVD: IRON_NUGGET
flashbangs:
  - Flashbang
flash-radius: 30
flash-bypass-blacklist:
  - GLASS
  - GLASS_PANE
shotguns:
  SPAS: 10
  AA12: 10
headshot:
  custom-sound: false
  helmet-sound: "ENTITY_ZOMBIE_DEATH"
  no-helmet-sound: "ENTITY_IRON_GOLEM_ATTACK"
knockback:
  disable: true
  custom:
    damage-percent: true
    value: 0.00888
