name: CustomCSWeapon
main: com.ericlam.mc.csweapon.CustomCSWeapon
version: 1.5.8
api-version: "1.13"
author: Hydranapse_
depend: [CrackShotPlus, CrackShot, HyperNiteMC-Core]
commands:
  csw-reload:
    description: reload command
  csw-scope:
    description: left click scope or sneak scope
